#!/usr/bin/env bash
# This script ping an IP adress
# Take an argument if argument empty diplay a message
if [ "$1" ]; then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
