#!/usr/bin/env bash
# This script replace the Ip adress of localhost
# and attribute an Ip adress to facebook.com

sed "s/127.0.0.1	localhost/127.0.0.2	localhost/" /etc/hosts
sed "a/8.8.8.8	facebook.com/" /etc/hosts